# Generated by Django 5.2.8 on 2025-11-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='Unknown Airline', max_length=100, verbose_name='Airline'),
            preserve_default=False,
        ),
    ]
